### ISSUE TITLE
Use of const in strict mode

### ISSUE THREAD

**Issue by adpking** [paulcbetts/xvfb-maybe#1]
**Origin:** Obtained through `npm install xvfb-maybe -g`
**Command:** `xvfb-maybe ./node_modules/electron-prebuilt/dist/electron app.js`

```
/usr/local/lib/node_modules/xvfb-maybe/src/xvfb-maybe.js:5
const spawnOg = require('child_process').spawn;
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by adpking** [comment]
My bad, forgot that I had recently re-installed my servers' operating system and node was outdated! Sorry.
